## Array Initialization

In [1]:
import numpy as np

In [2]:
arr=[[10,20,30,40,50]]
nparr=np.array(arr,np.int32)

In [3]:
nparr

array([[10, 20, 30, 40, 50]], dtype=int32)

In [4]:
nparr[0,3]

np.int32(40)

In [5]:
nparr[0,2]=100

In [6]:
nparr

array([[ 10,  20, 100,  40,  50]], dtype=int32)

## 2D Array Initialization

In [8]:
array=[[10,20,30],[10,80,40]]
nparray=np.array(array)

In [9]:
nparray

array([[10, 20, 30],
       [10, 80, 40]])

In [10]:
nparray.size

6

In [11]:
nparray.shape

(2, 3)

In [12]:
nparray.dtype

dtype('int64')